### ISSUE TITLE
Error during actor creation due to misconfiguration

### ISSUE THREAD

**Issue by mcampbell** [dnvriend/akka-persistence-inmemory#15]
I'm sure this is user error, but I am unsure how to get past it.  Help?

According to the docs, I shouldn't need any more than:
`akka.persistence.journal.plugin = "in-memory-journal"`, correct?
However, doing this yields the following error:
```
requirement failed: 'reference.conf' is missing persistence plugin config path: 'akka.persistence.journal.in-memory-journal'
akka.actor.ActorInitializationException: exception during creation
```

Using `akka.persistence.journal.plugin = "akka.persistence.journal.in-memory-journal"` yields the same results.

I have
```
  <repositories>
    <repository>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>central</id>
      <name>bintray</name>
      <url>http://dl.bintray.com/dnvriend/maven</url>
    </repository>
  </repositories>
...
    <dependency>
      <groupId>com.github.dnvriend</groupId>
      <artifactId>akka-persistence-inmemory_2.11</artifactId>
      <version>1.1.3</version>
    </dependency>
```

in my pom.

**Comment by eshepelyuk** [comment]
Well, the README explicitely says that you need this in `application.conf`
```
akka { 
  persistence { 
    journal.plugin = "inmemory-journal" 
    snapshot-store.plugin = "inmemory-snapshot-store" 
  }
}
```

As for me the error maybe caused by typo in plugin name.
It must be `inmemory-journal` not `in-memory-journal` as in your question.

**Comment by dnvriend** [comment]
Good tip, is the issue resolved? If not, do you have an example available somewhere, maybe in Github that we can check out?

**Comment by eshepelyuk** [comment]
@mcampbell any updates ? can this issue be closed ?

**Comment by voroninp** [comment]
@dnvriend I have exactly the same error, though I use 'inmemory-journal' in (test/resources/application.conf)

lib. version is 2.4.17.3
