### ISSUE TITLE
Persistence Query JavaDsl

### ISSUE THREAD

**Issue by dpfeiffer** [dnvriend/akka-persistence-inmemory#19]
It would be cool if we there was the JavaDsl implementation for the read journal. I prepared it for the 1.1.6 version because we ware currently on AKKA 2.4.1 but I could also do it for the current version and create a pull request. 

I would suggest to simply do it like the MongoDB AKKA persistence plugin: https://github.com/scullxbones/akka-persistence-mongo/blob/master/common/src/main/scala/akka/contrib/persistence/mongodb/MongoReadJournal.scala

I am also not sure how to test this, any ideas about that without a lot of duplicated test code?

**Comment by dnvriend** [comment]
Hi, I have added JavaDSL support, enjoy!
