### ISSUE TITLE
Publish to Maven Central or jCenter

### ISSUE THREAD

**Issue by hseeberger** [dnvriend/akka-persistence-inmemory#23]
If you need help, take a look at https://github.com/hseeberger/akka-sse.

**Comment by dnvriend** [comment]
Hi Heiko. I will look into the issue. Until that time, please add the following to your sbt build definition to use the plugin:

```scala
resolvers += "dnvriend at bintray" at "http://dl.bintray.com/dnvriend/maven"

libraryDependencies += "com.github.dnvriend" %% "akka-persistence-inmemory" % "1.2.8"
```

**Comment by hseeberger** [comment]
No worries, I did that ;-)
Very nice library!

**Comment by hseeberger** [comment]
BTW, you can use `resolvers += Resolver.bintray("dnvriend", "maven")`.

**Comment by dnvriend** [comment]
Thanks, doing my best. I use the plugin for `akka-persistence` and `akka-cluster` projects, as the in-memory plugin that comes with akka only does journalling. As for the resolver; I didn't know that :)

**Comment by dnvriend** [comment]
Hi Heiko, do you (need to) sign the artifacts. JCenter is complaining about missing .asc (PGP) signed artifacts.

**Comment by hseeberger** [comment]
Yes. Look at how akka-sse is using sbt-pgp:
```
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.0")
```
Then use `publishSigned` instead of `publish`.

**Comment by hseeberger** [comment]
Alternatively you could give automatic signing by Bintray a try ...

**Comment by dnvriend** [comment]
Thanks, puzzling on :)

**Comment by dnvriend** [comment]
It should be available on JCenter:

**Comment by hseeberger** [comment]
Nice! Can't find it on Maven Central, though. Did you press the button?

**Comment by dnvriend** [comment]
Yes I did! :) It should be available according to [The Central Repository Search](http://search.maven.org/#artifactdetails%7Ccom.github.dnvriend%7Cakka-persistence-inmemory_2.11%7C1.2.11%7Cjar)

**Comment by hseeberger** [comment]
Oops, that's a new version! Hence I could not find it ;-) Thanks!
