### ISSUE TITLE
Issues using akka-persistence-memory with fun-cqrs

### ISSUE THREAD

**Issue by saqibsaleem-ee** [dnvriend/akka-persistence-inmemory#25]
Hi.

I am trying to use funCQRS with the inmemory backend but I am having some issues. 
The command side works fine and it seems that I can save data.
What doesn't seem to work is the projection side and I was asked by the maintainer of funCQRS to check the config for the backend. From the docs it seems that the only config required is:

akka.persistence {
    journal.plugin = "inmemory-journal"
    snapshot-store.plugin = "inmemory-snapshot-store"
}

Is this all the config needed?

Again funCQRS mentioned that we need another entry in the application.conf:

akka.persistence {
    tagger = "io.funcqrs.akka.DomainEventTagAdapter"
}

But, I see no mention of this anywhere in the docs here.

Thanks in advance.

**Comment by saqibsaleem-ee** [comment]
Here is a sample project.

[funcqrs-spike.zip](https://github.com/dnvriend/akka-persistence-inmemory/files/256973/funcqrs-spike.zip)

**Comment by dnvriend** [comment]
Hi,

I don't know fun-cqrs. The inmemory journal can be configured as stated on the readme.md. There was a typo in it because I copied the contents from the jdbc plugin which basically does the same. The configuration should be:

```
akka.persistence {
    journal.plugin = "inmemory-journal"
    snapshot-store.plugin = "inmemory-snapshot-store"
}

inmemory-journal {
  event-adapters {
    tagging = "com.github.dnvriend.TaggingEventAdapter"
  }
  event-adapter-bindings {
    "com.github.dnvriend.Person$PersonCreated" = tagging
    "com.github.dnvriend.Person$FirstNameChanged" = tagging
    "com.github.dnvriend.Person$LastNameChanged" = tagging
  }
}
```

The example was taken from the [akka persistence demo project](https://github.com/dnvriend/demo-akka-persistence-jdbc).
