### ISSUE TITLE
Ability to get all saved snaphots

### ISSUE THREAD

**Issue by kbalyasnikov** [dnvriend/akka-persistence-inmemory#29]
For now there is `SnapshotForMaxSequenceNr` message in `InMemorySnapshotStorage`, but it returns just one snapshot. It would be great to have a message like `Snapshots` to get all snapshots by `persistenceId`. It is useful in testing scenarios where someone need to test proper snapshot saving and deletion.

**Comment by dnvriend** [comment]
For this use case would  the following suffice? By overriding recovery, in your unit test you could set the SnapshotSelectionCriteria as described in the [akka-persistence documentation](http://doc.akka.io/docs/akka/2.4/scala/persistence.html#Snapshots). This way you can assert whether or not the correct snapshot has been deleted.

```scala
class FooActor(override val recovery: Recovery, override val persistenceId: String) extends PersistentActor {
  override def receiveRecover: Receive = ???

  override def receiveCommand: Receive = ???
}
```

**Comment by dnvriend** [comment]
Could you please close this issue or is it still relevant?
