### ISSUE TITLE
Native call in Cassandra UUIDs causes journal to hang

### ISSUE THREAD

**Issue by rcavalcanti** [dnvriend/akka-persistence-inmemory#32]
Hi @dnvriend 

You will be amazed by this one.

The cassandra UUDs utility class has a native call to collect the process id. 
This happen on this line:
https://github.com/datastax/java-driver/blob/af5a17c028b44defc675fb0145e56cd8cd45b651/driver-core/src/main/java/com/datastax/driver/core/utils/UUIDs.java#L155

It turns out that this hangs depending on your system + jvm version. I'm on a Mac OS Siena running Java 1.8.121.

It hangs only on the first persisted event. When the first `JournalEntry` is initialised. After that the bug won't happen anymore because it relies on a static global variable inside the cassandra driver. `PosixLoader.GETPID_AVAILABLE` to be precise. 

The consequence of this is that the first event ever persisted block the actor for quite a while and the caller gets a timeout.

I have tried to work around it by initialising the PID earlier, but wasn't successful. 

Currently, I initialise it on a support test class in Fun.CQRS, but obviously the solution must be added to the plugin instead. 
(see https://github.com/strongtyped/fun-cqrs/blob/feature/75-path-dependent-types/modules/akka/src/test/scala/io/funcqrs/akka/AkkaBackendSupport.scala#L27)

**Comment by dnvriend** [comment]
Thanks for the update, who would have thought.. I actually still use 1.8.0_112!

In the latest version of the inmemory plugin I actually do not use the cassandra implementation anymore. The whole dependency is gone. For testing purposes I do not need that piece of code to generate a really unique UUID, so I have copied a piece of the UUID generation code and put it in the inmemory plugin and removed that piece.

see: https://github.com/dnvriend/akka-persistence-inmemory/blob/master/src/main/scala/akka/persistence/inmemory/util/UUIDs.java

**Comment by rcavalcanti** [comment]
That's good news. And it's also a good solution. No unnecessary deps.

I'm closing the issue as it became obsolete.

**Comment by rcavalcanti** [comment]
Hi @dnvriend 

I updated Fun.CQRS to use version 2.4.17.2, but the problem persist. 
https://github.com/strongtyped/fun-cqrs/blob/develop/project/Dependencies.scala#L32
https://github.com/strongtyped/fun-cqrs/blob/develop/modules/akka/src/test/scala/io/funcqrs/akka/AkkaBackendSupport.scala#L27

I still need to force a call to `akka.persistence.inmemory.nowUuid` in the `beforeAll` of all my tests.

This contradict my error report above, because now I'm not using the Cassandra one anymore. 

This error can hit other users as well and it's a very puzzling one.

**Comment by rcavalcanti** [comment]
And this is a Fun.CQRS branche where I'm using the in-memory plugin sources as dependency. Can be useful if you need / want to investigate further. You will need to fix the path to your checkout (see build.sbt).
 
https://github.com/strongtyped/fun-cqrs/tree/feature/plugin-fix

I might not have time to investigate it before the second week of March. 

It's also hard to debug it. The cassandra lib was logging a line once the underlying utility was ready to start generating UUIDs. Adding some logging in your UUIDs might help.

**Comment by dnvriend** [comment]
@rcavalcanti 

I have updated my JVM to 1.8.0_121 and put some debug lines in the package object and I get the 
following [sbt_output.txt](https://github.com/dnvriend/akka-persistence-inmemory/files/795804/sbt_output.txt). Total time of the tests is 3 seconds. Calculating the UUID doesn't take long, and also there appears to be no concurrency issue. I have created test that checks for some concurrency issues, but there doesn't seem to be any. Do you have a test where I can see the timeout?

```
import java.util.UUID

import akka.persistence.inmemory.TestSpec

import scala.concurrent.Future

class ConcurrentUUIDTest extends TestSpec {
  def getNow(x: Any): Future[UUID] = Future(akka.persistence.inmemory.nowUuid)
  it should "get uuids concurrently" in {
    Future.sequence((1 to 1000).map(getNow)).futureValue
  }
}
```

**Comment by rcavalcanti** [comment]
`AggregateManagerTest` and `CommandTimeoutTest` suffers from that. 

Do you have Mac OS X Sierra?

**Comment by dnvriend** [comment]
@rcavalcanti 

I have removed all code that tries to determine the ethernet hardware address (the only thing I can think of what can cause IO waits). For testing you don't to determine the unique node anyway because it should be a single node test. You could try to check out akka-persistence-inmemory and do a publishLocal, and set the dependency to `2.4.17.3-SNAPSHOT` and try if it works. 

I have pushed the changes to the master branch of akka-persistence-inmemory.

**Comment by rcavalcanti** [comment]
It works! Thanks.

That was probably that. I do think it's related with Java version + Mac OS version. 

I don't have that problem on my previous Mac.

**Comment by dnvriend** [comment]
Thanks for trying it out. I will release a new version shortly. I am also running OSX Sierra 10.12.3. 

I'm just wondering and of course it could be unrelated. Does your docker-compose take a long time to launch (if you are using it). Maybe there is a problem with your `/etc/hosts` file. After updating to Sierra I had the problem that docker-compose took a long time to launch and I had to add the following to my `/etc/hosts` file:

```
127.0.0.1 localhost
127.0.0.1 localunixsocket
127.0.0.1 localunixsocket.lan
127.0.0.1 localunixsocket.local
127.0.0.1 localunixsocket.home MacBook-Pro-van-Dennis.local.home
127.0.0.1 localunixsocket.local
```

**Comment by rcavalcanti** [comment]
I do use docker and never had issues with it (not related with network). 

It's possible that there is something special with my system, although is a brand new one. I didn't tweaked it at all. 

Anyway, seems that the problem is solved. Thanks for that.
