### ISSUE TITLE
InMemoryReadJournal.eventsByPersistenceId returns deleted messages

### ISSUE THREAD

**Issue by davidcorcoran** [dnvriend/akka-persistence-inmemory#33]
In commit `9ce9a6b` "find deleted messages" you changed the way `currentEventsByPersistenceId` (and therefore `eventsByPersistenceId`) worked so that they now return deleted messages. I think the expected behaviour for them would be to not return deleted messages. I believe that's how your `akka-persistence-jdbc` library works, messages flagged as deleted are filtered out.

I stumbled across this while writing test code which was supposed to test that the correct messages we're being deleted, but the journal was always returning them despite the fact they were deleted.

So I think this is a bug, but could be wrong.

Thanks

**Comment by dnvriend** [comment]
Thanks for creating the issue. I'll take a look at it.

**Comment by dnvriend** [comment]
You were absolutely correct, it was a bug. It should be fixed in release v2.4.17.2 and should be synced on Maven Central the following hours/days.

**Comment by davidcorcoran** [comment]
I've updated to v2.4.17.2 this morning and my tests which were previously failing are now passing. Thank you for fixing the bug and for fixing it so quickly. Both this and `akka-persistence-jdbc` are great libraries.

**Comment by dnvriend** [comment]
Thanks!
