### ISSUE TITLE
SnapshotStorage dead letter

### ISSUE THREAD

**Issue by sarahprecious** [dnvriend/akka-persistence-inmemory#34]
I encountered an error of dead letter sent to snapshotstorage when saving snapshot. Any advice of what could be the issue. I didn't change any of the default configurations.

**Comment by dnvriend** [comment]
Hi, I created a test project called [akka-persistence-inmemory-test](https://github.com/dnvriend/akka-persistence-inmemory-test), it seems to work just fine. Maybe you can check the differences?

**Comment by sarahprecious** [comment]
Thanks for getting back.
I can hardly compare because I am using it in java in akka 2.4 and I am only using snapshot in the actor.
I was trying it out by putting the default configurations in my app's application.conf. It resulted in the dead letter. When I remove those configurations, the dead letter didn't appear but the recovery didn't work. There was no snapshot offered when the actor was recreated.

**Comment by dnvriend** [comment]
I must admit, I only use Scala in combination with Akka so maybe I'm not of much help to you. The data type you are serializing, does it extend the marker interface `java.io.Serializable`?
