### ISSUE TITLE
no serializer for internal plugin messages

### ISSUE THREAD

**Issue by kpbochenek** [dnvriend/akka-persistence-inmemory#35]
During testing I have `akka.actor.serialize-messages = on`  (with = off everything works ok)
It means every message sent through tell / ask will be serialized then deserialized then placed to actor mailbox.

All my messages inherit from one trait and I provide serializer for this trait.
Also akka handles it's own internal messages with custom serializer (protobuf I think).

Messages sent internally in this plugin have no defined serializer and default java serializer is used.

In my particular case I hit trouble in this line:
https://github.com/dnvriend/akka-persistence-inmemory/blob/master/src/main/scala/akka/persistence/inmemory/journal/InMemoryAsyncWriteJournal.scala#L77

`WriteList` is sent to actor which means akka will serialize and deserialize this message.
Because there is no special serializer a default java one will be used.
But this object stores my classed internally which means java serializer will be applied to my classes but it will cause serialization to fail because they must be serialized with my serializer.

One possible idea could be to extend `JournalCommand` with `NoSerializationVerificationNeeded` which will force akka to skip serialization of these messages even though `serialize-messages = on`.

**Comment by dnvriend** [comment]
Thanks for the ticket, I've released v2.4.18.1 and v2.5.1.1 that should fix the issue.

**Comment by kpbochenek** [comment]
Thanks for quick fix! I will try bump version, switch to `serialize-messages = on` and let you know if it solves all problems.

**Comment by kpbochenek** [comment]
Not sure how it works but would it be possible to also push to mvnrepository?
or is it populated with some delay and I should wait?

https://mvnrepository.com/artifact/com.github.dnvriend/akka-persistence-inmemory_2.11

**Comment by dnvriend** [comment]
mvn has been known to have synchronization issues, give it some time :)

**Comment by kpbochenek** [comment]
Forgot to respond, works perfectly, you can close this ticket,

Cheers
