### ISSUE TITLE
[question] Instanciating the read-journal

### ISSUE THREAD

**Issue by rcavalcanti** [dnvriend/akka-persistence-inmemory#37]
Hi Dennis, 

On the README file you show how to instantiate the read journal in Scala as such:

```scala
lazy val readJournal = PersistenceQuery(system).readJournalFor("inmemory-read-journal")
 .asInstanceOf[ReadJournal
    with CurrentPersistenceIdsQuery
    with AllPersistenceIdsQuery
    with CurrentEventsByPersistenceIdQuery
    with CurrentEventsByTagQuery
    with EventsByPersistenceIdQuery
    with EventsByTagQuery]
```

Why aren't you promoting it like the following?
```scala
  lazy val readJournal =
    PersistenceQuery(system)
      .readJournalFor[InMemoryReadJournal](InMemoryReadJournal.Identifier)
```

It's not only conciser, but also less error prone. Any thoughts?

**Comment by dnvriend** [comment]
Hi Renato. That is a good question. The idea behind the readme(s) on my projects in general is instructional and educational. akka-persistence-inmemory is most often used for testing, so the consuming code shouldn't be bound to a specific read journal implementation. The first code shows a way define a general read journal, where eg. by means of configuration; ie. the plugin-id, can be used to switch implementations. The second code is much shorter but binds the consumer to the InMemoryReadJournal definition. As always it all depends on your use case of course and how much dependency you need from your consumer to your libraries. That said, I have no bias one way or the other.

**Comment by rcavalcanti** [comment]
Fair enough Dennis.
I didn't realised that the more verbose one is not depending on in-memory plugin. Your readme turns out to be very educational for me. ;-) 

Thanks!
