### ISSUE TITLE
2.4-M3 Compatibility

### ISSUE THREAD

**Issue by TimPigden** [dnvriend/akka-persistence-inmemory#4]
Hi - it would be brilliant if you could update for M3 compatibility, since I'm desperate to get my hands on all the new persistence goodies but all my akka persistence unit tests use inmemory so I never have to worry about existing state.

"Old Akka Persistence plugins released for 2.3 are not compatible with the changes that were done in 2.4-M2. We do not plan to do more changes to the plugin API so now is a good time for Akka Persistence plugin maintainers to migrate and release a preview for 2.4-M3.  Even though there are rather many API changes since 2.3 in the Persistence plugin API it should not be difficult to migrate. "

**Comment by dlisin** [comment]
I will try to submit fix today

**Comment by dnvriend** [comment]
Thanks, to be honest, I haven't payed much attention to Akka 2.4; [akka-stream & akka-http](http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala.html) took my full attention. Now that akka 2.4's API has somewhat stabilized I will look into it, in particular:
- [persistence](http://doc.akka.io/docs/akka/2.4-M3/scala/persistence.html) sections
- [persistence - schema evolution](http://doc.akka.io/docs/akka/2.4-M3/scala/persistence-schema-evolution.html) 
- [persistence - query](http://doc.akka.io/docs/akka/2.4-M3/scala/persistence-query.html). 

@dlisin: Thanks in advance!

**Comment by TimPigden** [comment]
belated "thanks" - I've been on holiday

On 24 August 2015 at 09:39, Dennis Vriend <notifications@github.com> wrote:

> Closed #4 <https://github.com/dnvriend/akka-persistence-inmemory/issues/4>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnvriend/akka-persistence-inmemory/issues/4#event-390278413>
> .
>



-- 
Tim Pigden
Optrak Distribution Software Limited
+44 (0)1992 517100
http://www.linkedin.com/in/timpigden
http://optrak.com
Optrak Distribution Software Ltd is a limited company registered in England
and Wales.
Company Registration No. 2327613 Registered Offices: Suite 6,The Maltings,
Hoe Lane, Ware, SG12 9LR England
This email and any attachments to it may be confidential and are intended
solely for the use of the individual to whom it is addressed. Any views or
opinions expressed are solely those of the author and do not necessarily
represent those of Optrak Distribution Software Ltd. If you are not the
intended recipient of this email, you must neither take any action based
upon its contents, nor copy or show it to anyone. Please contact the sender
if you believe you have received this email in error.
