### ISSUE TITLE
Should not use scheduler with repeat-delay=0

### ISSUE THREAD

**Issue by synox** [dnvriend/akka-persistence-inmemory#43]
In [InMemoryReadJournal](https://github.com/dnvriend/akka-persistence-inmemory/blob/master/src/main/scala/akka/persistence/inmemory/query/scaladsl/InMemoryReadJournal.scala#L91) there is a repeat with zero delay:  
`Source.tick(refreshInterval, 0.seconds, 0)`

Why is zero used as repeat delay? Using 10 Miliseconds would solve the problem with the following combination:

When using https://github.com/miguno/akka-mock-scheduler this causes a infinite loop.
The Problem is an implementation detail, that results in an endless-loop when using repeat-delay=zero. 
(See https://github.com/miguno/akka-mock-scheduler/blob/develop/src/main/scala/com/miguno/akka/testing/MockScheduler.scala#L33)

**Comment by dnvriend** [comment]
Thanks, for the info!
