### ISSUE TITLE
Use system actors to enable testing in Akka Typed

### ISSUE THREAD

**Issue by hseeberger** [dnvriend/akka-persistence-inmemory#50]
See https://github.com/akka/akka/issues/24861.

**Comment by hseeberger** [comment]
Awesome, please release 😉

**Comment by dnvriend** [comment]
Done `2.4.20.0`.

**Comment by hseeberger** [comment]
YAY!

**Comment by hseeberger** [comment]
Ah, wait, I need a 2.5 version!

**Comment by IainHull** [comment]
Hi I am trying to uptake this fix but its published with Java 10. Would you be able to republish with Java 8? (See #58)
