### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by thjaeckle** [dnvriend/akka-persistence-inmemory#6]
Hi there.

Would it be possible to also add your releases to Maven Central again? I only see version 0.0.2 there:
http://search.maven.org/#artifactdetails|com.github.dnvriend|akka-persistence-inmemory_2.11|0.0.2|jar

I am aware the artifacts just moved to bintray - but which administrator of a (corporate) Maven proxy would add a "foreign" repository for each library the developers need? ;)

**Comment by dnvriend** [comment]
I will try to set up bintray to it will sync certain libraries to Maven Central.

**Comment by thjaeckle** [comment]
Cool, Thanks :+1:

**Comment by thjaeckle** [comment]
Any luck setting up the sync?

**Comment by dnvriend** [comment]
No, as I thought, that's why the project moved to Bintray. Same issues as I had before with every release, sonatype is a pain..
