### ISSUE TITLE
Missing support for keyspace similar to akka-persistence-cassandra

### ISSUE THREAD

**Issue by BeatSager** [dnvriend/akka-persistence-inmemory#66]
In our product we use this great plugin as well when we start up the developers local servers. We have many applications running store their data in deployed environment in different cassandra keyspaces. In order to test all this applications together we need this feature as well local in memory.

As discussed in https://github.com/dnvriend/akka-persistence-inmemory/pull/39 I created https://github.com/dnvriend/akka-persistence-inmemory/pull/59

**Comment by dnvriend** [comment]
Please see PR #59 and implement your own persistence strategy.
